"""Document Lifecycle — lifecycle management, versioning, approvals, reviews, and retention."""

from __future__ import annotations

from eaip.document_lifecycle.events import (
    DocumentApproved,
    DocumentArchived,
    DocumentAuditLogged,
    DocumentCreated,
    DocumentDeleted,
    DocumentExpired,
    DocumentExpiryWarningSent,
    DocumentLifecycleEvent,
    DocumentLifecyclePolicyApplied,
    DocumentLifecycleReportGenerated,
    DocumentRejected,
    DocumentRestored,
    DocumentRetentionPolicyEnforced,
    DocumentReviewCompleted,
    DocumentReviewed,
    DocumentReviewRequested,
    DocumentStatusChanged,
    DocumentUpdated,
    DocumentVersioned,
)
from eaip.document_lifecycle.exceptions import (
    DocumentApprovalError,
    DocumentArchiveError,
    DocumentExpiryError,
    DocumentLifecycleError,
    DocumentNotFoundError,
    DocumentRetentionError,
    DocumentReviewError,
    DocumentStatusError,
    DocumentVersionError,
)
from eaip.document_lifecycle.health import DocumentLifecycleHealthCheck
from eaip.document_lifecycle.integration import DocumentLifecycleRuntimeModule
from eaip.document_lifecycle.models import (
    DocumentApprovalWorkflow,
    DocumentAuditEntry,
    DocumentExpiryConfig,
    DocumentLifecycle,
    DocumentLifecycleAction,
    DocumentLifecycleActionType,
    DocumentLifecycleConfig,
    DocumentLifecyclePolicy,
    DocumentLifecycleReport,
    DocumentLifecycleStage,
    DocumentLifecycleStatus,
    DocumentLifecycleTransition,
    DocumentRetentionPolicy,
    DocumentReview,
    DocumentRevision,
    DocumentVersion,
    DocumentVersionStatus,
    ReviewStatus,
)
from eaip.document_lifecycle.service import DocumentLifecycleService

__all__ = [
    "DocumentApprovalError",
    "DocumentApprovalWorkflow",
    "DocumentApproved",
    "DocumentArchiveError",
    "DocumentArchived",
    "DocumentAuditEntry",
    "DocumentAuditLogged",
    "DocumentCreated",
    "DocumentDeleted",
    "DocumentExpired",
    "DocumentExpiryConfig",
    "DocumentExpiryError",
    "DocumentExpiryWarningSent",
    "DocumentLifecycle",
    "DocumentLifecycleAction",
    "DocumentLifecycleActionType",
    "DocumentLifecycleConfig",
    "DocumentLifecycleError",
    "DocumentLifecycleEvent",
    "DocumentLifecycleHealthCheck",
    "DocumentLifecyclePolicy",
    "DocumentLifecyclePolicyApplied",
    "DocumentLifecycleReport",
    "DocumentLifecycleReportGenerated",
    "DocumentLifecycleRuntimeModule",
    "DocumentLifecycleService",
    "DocumentLifecycleStage",
    "DocumentLifecycleStatus",
    "DocumentLifecycleTransition",
    "DocumentNotFoundError",
    "DocumentRejected",
    "DocumentRestored",
    "DocumentRetentionError",
    "DocumentRetentionPolicy",
    "DocumentRetentionPolicyEnforced",
    "DocumentReview",
    "DocumentReviewCompleted",
    "DocumentReviewError",
    "DocumentReviewRequested",
    "DocumentReviewed",
    "DocumentRevision",
    "DocumentStatusChanged",
    "DocumentStatusError",
    "DocumentUpdated",
    "DocumentVersion",
    "DocumentVersionError",
    "DocumentVersionStatus",
    "DocumentVersioned",
    "ReviewStatus",
]
