"""Administrative API management — definitions, versions, endpoints, clients, documentation."""

from __future__ import annotations

from eaip.admin_api.events import (
    ApiAuditLogged,
    ApiClientActivated,
    ApiClientCreated,
    ApiClientDeactivated,
    ApiClientDeleted,
    ApiClientTokenRotated,
    ApiClientUpdated,
    ApiDefinitionCreated,
    ApiDefinitionDeleted,
    ApiDefinitionUpdated,
    ApiDocumentationGenerated,
    ApiEndpointAdded,
    ApiEndpointRemoved,
    ApiEndpointUpdated,
    ApiRequestReceived,
    ApiResponseSent,
    ApiUsageMetricCollected,
    ApiVersionDeprecated,
    ApiVersionReleased,
    ApiVersionRetired,
)
from eaip.admin_api.exceptions import (
    AdminApiError,
    ApiAuthError,
    ApiClientError,
    ApiDefinitionNotFoundError,
    ApiEndpointError,
    ApiRateLimitError,
    ApiSpecificationError,
    ApiUsageError,
    ApiVersionError,
)
from eaip.admin_api.health import AdminApiHealthCheck
from eaip.admin_api.integration import AdminApiRuntimeModule
from eaip.admin_api.models import (
    ApiAuditEntry,
    ApiAuthScheme,
    ApiClient,
    ApiClientPermission,
    ApiClientStatus,
    ApiClientToken,
    ApiDefinition,
    ApiDocumentation,
    ApiEndpoint,
    ApiHealthEndpoint,
    ApiMethod,
    ApiRateLimit,
    ApiRequest,
    ApiResponse,
    ApiSpecification,
    ApiSwaggerConfig,
    ApiThrottleConfig,
    ApiUsageMetric,
    ApiVersion,
    ApiVersionStatus,
)
from eaip.admin_api.service import AdminApiService

__all__ = [
    "AdminApiError",
    "AdminApiHealthCheck",
    "AdminApiRuntimeModule",
    "AdminApiService",
    "ApiAuditEntry",
    "ApiAuditLogged",
    "ApiAuthError",
    "ApiAuthScheme",
    "ApiClient",
    "ApiClientActivated",
    "ApiClientCreated",
    "ApiClientDeactivated",
    "ApiClientDeleted",
    "ApiClientError",
    "ApiClientPermission",
    "ApiClientStatus",
    "ApiClientToken",
    "ApiClientTokenRotated",
    "ApiClientUpdated",
    "ApiDefinition",
    "ApiDefinitionCreated",
    "ApiDefinitionDeleted",
    "ApiDefinitionNotFoundError",
    "ApiDefinitionUpdated",
    "ApiDocumentation",
    "ApiDocumentationGenerated",
    "ApiEndpoint",
    "ApiEndpointAdded",
    "ApiEndpointError",
    "ApiEndpointRemoved",
    "ApiEndpointUpdated",
    "ApiHealthEndpoint",
    "ApiMethod",
    "ApiRateLimit",
    "ApiRateLimitError",
    "ApiRequest",
    "ApiRequestReceived",
    "ApiResponse",
    "ApiResponseSent",
    "ApiSpecification",
    "ApiSpecificationError",
    "ApiSwaggerConfig",
    "ApiThrottleConfig",
    "ApiUsageError",
    "ApiUsageMetric",
    "ApiUsageMetricCollected",
    "ApiVersion",
    "ApiVersionDeprecated",
    "ApiVersionError",
    "ApiVersionReleased",
    "ApiVersionRetired",
    "ApiVersionStatus",
]
