"""Canonical EAIP Platform Capability Inventory.

Defines the authoritative initial inventory of platform capabilities derived from
active repository code, routes, services, and APIs.
"""

from __future__ import annotations

from eaip.capabilities.capability import (
    Capability,
    CapabilityCategory,
    CapabilityStatus,
    OperationType,
)
from eaip.capabilities.registry import CapabilityRegistry

CANONICAL_CAPABILITIES: tuple[Capability, ...] = (
    Capability(
        name="eaip.dashboard",
        title="Operational Dashboard",
        description="Central operational view of platform health, activity, and telemetry.",
        version="1.0.0",
        status=CapabilityStatus.ENABLED,
        capability_id="dashboard",
        category=CapabilityCategory.OPERATIONAL,
        domain="eaip",
        owner="platform-core",
        lifecycle_state="active",
        routes=("/dashboard",),
        navigation_references=("nav.dashboard",),
        api_operations=("GET /api/v1/dashboard/overview", "GET /api/v1/health"),
        events=("eaip.dashboard.viewed",),
        entities=("DashboardOverview", "HealthSummary"),
        assistant_description="Provides system overview, key operational metrics, and quick status checks.",
        tour_metadata={"step_id": "dashboard", "order": "0"},
        search_terms=("overview", "metrics", "health", "system status", "telemetry"),
        documentation_references=("docs/dashboard.md",),
        supported_operations=(OperationType.READ, OperationType.QUERY),
        tags=("core", "ui", "dashboard", "monitoring"),
    ),
    Capability(
        name="eaip.agents",
        title="Autonomous Agents",
        description="Lifecycle management, execution, and monitoring of enterprise agents.",
        version="1.0.0",
        status=CapabilityStatus.ENABLED,
        capability_id="agents",
        category=CapabilityCategory.INTELLIGENCE,
        domain="eaip",
        owner="agent-runtime",
        lifecycle_state="active",
        routes=("/agents", "/agents/[id]"),
        navigation_references=("nav.agents",),
        api_operations=(
            "GET /api/v1/agents",
            "POST /api/v1/agents",
            "POST /api/v1/agents/{id}/execute",
        ),
        events=("agent.registered", "agent.started", "agent.completed", "agent.failed"),
        entities=("Agent", "AgentExecution", "AgentMetrics"),
        assistant_description="Discovers, inspects, and invokes registered enterprise agents.",
        tour_metadata={"step_id": "agents", "order": "1"},
        search_terms=("agents", "workers", "automation", "bots", "executors"),
        documentation_references=("docs/agents.md",),
        related_capabilities=("eaip.orchestration", "eaip.workflows", "eaip.brains"),
        supported_operations=(
            OperationType.READ,
            OperationType.QUERY,
            OperationType.CREATE,
            OperationType.UPDATE,
            OperationType.DELETE,
            OperationType.EXECUTE,
            OperationType.PAUSE,
            OperationType.RESUME,
        ),
        tags=("agents", "intelligence", "execution"),
    ),
    Capability(
        name="eaip.brains",
        title="Second Brains",
        description="Governed cognitive knowledge repositories and reasoning instances.",
        version="1.0.0",
        status=CapabilityStatus.ENABLED,
        capability_id="brains",
        category=CapabilityCategory.INTELLIGENCE,
        domain="eaip",
        owner="knowledge-systems",
        lifecycle_state="active",
        routes=("/brains", "/brains/[id]"),
        navigation_references=("nav.brains",),
        api_operations=("GET /api/v1/brains", "POST /api/v1/brains", "PUT /api/v1/brains/{id}"),
        events=("brain.created", "brain.configured", "brain.accessed"),
        entities=("Brain", "BrainCollection", "BrainRecommendation"),
        assistant_description="Specialized enterprise knowledge instances connecting agents with governed context.",
        tour_metadata={"step_id": "brains", "order": "2"},
        search_terms=("second brain", "brains", "reasoning", "knowledge stores"),
        documentation_references=("docs/brains.md",),
        related_capabilities=("eaip.knowledge", "eaip.memory", "eaip.agents"),
        supported_operations=(
            OperationType.READ,
            OperationType.QUERY,
            OperationType.CREATE,
            OperationType.UPDATE,
            OperationType.DELETE,
        ),
        tags=("brains", "intelligence", "knowledge"),
    ),
    Capability(
        name="eaip.knowledge",
        title="Knowledge Base",
        description="Enterprise vector and structured knowledge retrieval and indexing.",
        version="1.0.0",
        status=CapabilityStatus.ENABLED,
        capability_id="knowledge",
        category=CapabilityCategory.INTELLIGENCE,
        domain="eaip",
        owner="knowledge-systems",
        lifecycle_state="active",
        routes=("/knowledge",),
        navigation_references=("nav.knowledge",),
        api_operations=("GET /api/v1/knowledge", "POST /api/v1/knowledge/search"),
        events=("knowledge.indexed", "knowledge.searched"),
        entities=("KnowledgeCollection", "KnowledgeDocument", "KnowledgeChunk"),
        assistant_description="Grounded documentation and policy repository used for accurate Q&A.",
        tour_metadata={"step_id": "knowledge", "order": "3"},
        search_terms=("knowledge", "documents", "articles", "policies", "rag"),
        documentation_references=("docs/knowledge.md",),
        related_capabilities=("eaip.brains", "eaip.search"),
        supported_operations=(
            OperationType.READ,
            OperationType.QUERY,
            OperationType.CREATE,
            OperationType.UPDATE,
            OperationType.DELETE,
        ),
        tags=("knowledge", "rag", "search"),
    ),
    Capability(
        name="eaip.memory",
        title="Enterprise Memory",
        description="Governed personal and organization memory with retention policies.",
        version="1.0.0",
        status=CapabilityStatus.ENABLED,
        capability_id="memory",
        category=CapabilityCategory.INTELLIGENCE,
        domain="eaip",
        owner="memory-service",
        lifecycle_state="active",
        routes=("/memory",),
        navigation_references=("nav.memory",),
        api_operations=("GET /api/v1/memory", "POST /api/v1/memory", "DELETE /api/v1/memory/{id}"),
        events=("memory.stored", "memory.consolidated", "memory.expired"),
        entities=("MemoryItem", "MemoryContext", "MemoryRetentionPolicy"),
        assistant_description="Persistent memory and preferences remembered across sessions.",
        tour_metadata={"step_id": "memory", "order": "9"},
        search_terms=("memory", "context", "history", "preferences"),
        documentation_references=("docs/memory.md",),
        related_capabilities=("eaip.conductor", "eaip.brains"),
        supported_operations=(
            OperationType.READ,
            OperationType.QUERY,
            OperationType.CREATE,
            OperationType.DELETE,
        ),
        tags=("memory", "governance", "assistant"),
    ),
    Capability(
        name="eaip.notifications",
        title="Notification Center",
        description="Enterprise notification routing, digest generation, and real-time delivery.",
        version="1.0.0",
        status=CapabilityStatus.ENABLED,
        capability_id="notifications",
        category=CapabilityCategory.OPERATIONAL,
        domain="eaip",
        owner="communications",
        lifecycle_state="active",
        routes=("/notifications",),
        navigation_references=("nav.notifications",),
        api_operations=("GET /api/v1/notifications", "PUT /api/v1/notifications/{id}/read"),
        events=("notification.created", "notification.read", "notification.dismissed"),
        entities=("NotificationItem", "NotificationPreferences", "NotificationDigest"),
        assistant_description="Surfaces alerts, mentions, task updates, and system broadcasts.",
        search_terms=("notifications", "alerts", "messages", "inbox"),
        documentation_references=("docs/notifications.md",),
        supported_operations=(
            OperationType.READ,
            OperationType.QUERY,
            OperationType.UPDATE,
            OperationType.DELETE,
        ),
        tags=("notifications", "alerts", "communication"),
    ),
    Capability(
        name="eaip.operations",
        title="Operations Management",
        description="Operational health dashboards, maintenance schedules, and platform runbooks.",
        version="1.0.0",
        status=CapabilityStatus.ENABLED,
        capability_id="operations",
        category=CapabilityCategory.OPERATIONAL,
        domain="eaip",
        owner="sre-platform",
        lifecycle_state="active",
        routes=("/operations",),
        navigation_references=("nav.operations",),
        api_operations=("GET /api/v1/operations", "POST /api/v1/operations/maintenance"),
        events=("operation.scheduled", "operation.completed"),
        entities=("OperationTask", "MaintenanceWindow", "Runbook"),
        assistant_description="Platform maintenance, system recovery, and operational procedures.",
        search_terms=("operations", "maintenance", "runbooks", "sre"),
        documentation_references=("docs/operations.md",),
        related_capabilities=("eaip.monitoring", "eaip.health"),
        supported_operations=(
            OperationType.READ,
            OperationType.QUERY,
            OperationType.EXECUTE,
            OperationType.APPROVE,
        ),
        tags=("operations", "sre", "maintenance"),
    ),
    Capability(
        name="eaip.workflows",
        title="Workflow Engine",
        description="State-machine based business process automation and step execution.",
        version="1.0.0",
        status=CapabilityStatus.ENABLED,
        capability_id="workflows",
        category=CapabilityCategory.OPERATIONAL,
        domain="eaip",
        owner="workflow-engine",
        lifecycle_state="active",
        routes=("/workflows", "/workflows/[id]"),
        navigation_references=("nav.workflows",),
        api_operations=("GET /api/v1/workflows", "POST /api/v1/workflows/{id}/trigger"),
        events=("workflow.started", "workflow.step_completed", "workflow.finished"),
        entities=("WorkflowDefinition", "WorkflowInstance", "WorkflowStep"),
        assistant_description="Executes, inspects, and pauses multi-step automated workflows.",
        search_terms=("workflows", "processes", "pipelines", "automation", "bpm"),
        documentation_references=("docs/workflows.md",),
        related_capabilities=("eaip.agents", "eaip.missions"),
        supported_operations=(
            OperationType.READ,
            OperationType.QUERY,
            OperationType.CREATE,
            OperationType.UPDATE,
            OperationType.DELETE,
            OperationType.EXECUTE,
            OperationType.PAUSE,
            OperationType.RESUME,
            OperationType.CANCEL,
        ),
        tags=("workflows", "automation", "bpm"),
    ),
    Capability(
        name="eaip.missions",
        title="Mission Orchestration",
        description="High-level mission planning, team allocation, and multi-agent coordination.",
        version="1.0.0",
        status=CapabilityStatus.ENABLED,
        capability_id="missions",
        category=CapabilityCategory.OPERATIONAL,
        domain="eaip",
        owner="orchestration-team",
        lifecycle_state="active",
        routes=("/missions", "/missions/[id]"),
        navigation_references=("nav.missions",),
        api_operations=("GET /api/v1/missions", "POST /api/v1/missions"),
        events=("mission.created", "mission.activated", "mission.completed"),
        entities=("Mission", "MissionPlan", "MissionAllocation"),
        assistant_description="Orchestrates multi-agent teams to complete structured objectives.",
        tour_metadata={"step_id": "missions", "order": "4"},
        search_terms=("missions", "goals", "objectives", "plans"),
        documentation_references=("docs/missions.md",),
        related_capabilities=("eaip.agents", "eaip.orchestration"),
        supported_operations=(
            OperationType.READ,
            OperationType.QUERY,
            OperationType.CREATE,
            OperationType.EXECUTE,
            OperationType.APPROVE,
            OperationType.CANCEL,
        ),
        tags=("missions", "orchestration", "goals"),
    ),
    Capability(
        name="eaip.monitoring",
        title="Telemetry & Monitoring",
        description="Real-time performance metrics, system alerts, and SLO tracking.",
        version="1.0.0",
        status=CapabilityStatus.ENABLED,
        capability_id="monitoring",
        category=CapabilityCategory.OPERATIONAL,
        domain="eaip",
        owner="observability",
        lifecycle_state="active",
        routes=("/monitoring",),
        navigation_references=("nav.monitoring",),
        api_operations=("GET /api/v1/monitoring/metrics", "GET /api/v1/monitoring/alerts"),
        events=("alert.triggered", "slo.breached"),
        entities=("MetricSeries", "AlertRule", "SLOTarget"),
        assistant_description="Monitors latency, errors, utilization, and system performance.",
        tour_metadata={"step_id": "monitoring", "order": "5"},
        search_terms=("monitoring", "telemetry", "metrics", "alerts", "slo"),
        documentation_references=("docs/monitoring.md",),
        related_capabilities=("eaip.health", "eaip.dashboard"),
        supported_operations=(OperationType.READ, OperationType.QUERY),
        tags=("monitoring", "observability", "metrics"),
    ),
    Capability(
        name="eaip.health",
        title="Health & Diagnostics",
        description="Subsystem health probes, dependency checking, and diagnostic tests.",
        version="1.0.0",
        status=CapabilityStatus.ENABLED,
        capability_id="health",
        category=CapabilityCategory.INFRASTRUCTURE,
        domain="eaip",
        owner="platform-core",
        lifecycle_state="active",
        routes=("/health",),
        navigation_references=("nav.health",),
        api_operations=("GET /api/v1/health", "GET /api/v1/diagnostics"),
        events=("health.degraded", "health.recovered"),
        entities=("HealthStatus", "DiagnosticReport"),
        assistant_description="Inspects individual service health, readiness, and connectivity.",
        search_terms=("health", "status", "uptime", "diagnostics"),
        documentation_references=("docs/health.md",),
        supported_operations=(OperationType.READ, OperationType.QUERY),
        tags=("health", "diagnostics", "infrastructure"),
    ),
    Capability(
        name="eaip.administration",
        title="Platform Administration",
        description="Tenant, user, role, permission, and enterprise configuration governance.",
        version="1.0.0",
        status=CapabilityStatus.ENABLED,
        capability_id="administration",
        category=CapabilityCategory.GOVERNANCE,
        domain="eaip",
        owner="security-admin",
        lifecycle_state="active",
        routes=("/administration", "/users", "/roles", "/permissions", "/settings"),
        navigation_references=("nav.administration",),
        api_operations=("GET /api/v1/admin/users", "POST /api/v1/admin/roles"),
        events=("user.created", "role.assigned", "permission.granted"),
        entities=("User", "Role", "Permission", "TenantSettings"),
        assistant_description="Governs identities, RBAC roles, tenant isolation, and security settings.",
        tour_metadata={"step_id": "administration", "order": "7"},
        search_terms=("admin", "users", "roles", "permissions", "settings", "rbac"),
        documentation_references=("docs/administration.md",),
        supported_operations=(
            OperationType.READ,
            OperationType.QUERY,
            OperationType.CREATE,
            OperationType.UPDATE,
            OperationType.DELETE,
            OperationType.APPROVE,
        ),
        tags=("admin", "security", "rbac", "governance"),
    ),
    Capability(
        name="eaip.search",
        title="Global Search",
        description="Unified federated search across knowledge, agents, actions, and settings.",
        version="1.0.0",
        status=CapabilityStatus.ENABLED,
        capability_id="search",
        category=CapabilityCategory.EXPERIENCE,
        domain="eaip",
        owner="search-platform",
        lifecycle_state="active",
        routes=("/search",),
        navigation_references=("nav.search",),
        api_operations=("GET /api/v1/search",),
        events=("search.performed",),
        entities=("SearchResult", "SearchQuery"),
        assistant_description="Fast federated search indexing all platform entities and documents.",
        search_terms=("search", "find", "lookup", "query"),
        documentation_references=("docs/search.md",),
        related_capabilities=("eaip.knowledge", "eaip.agents"),
        supported_operations=(OperationType.READ, OperationType.QUERY),
        tags=("search", "discovery", "federation"),
    ),
    Capability(
        name="eaip.reports",
        title="Reports & Analytics",
        description="Cost analytics, resource usage trends, and automated report generation.",
        version="1.0.0",
        status=CapabilityStatus.ENABLED,
        capability_id="reports",
        category=CapabilityCategory.OPERATIONAL,
        domain="eaip",
        owner="analytics-team",
        lifecycle_state="active",
        routes=("/reports", "/analytics", "/cost"),
        navigation_references=("nav.reports",),
        api_operations=("GET /api/v1/reports", "GET /api/v1/cost/summary"),
        events=("report.generated", "report.scheduled"),
        entities=("Report", "CostSummary", "AnalyticsTrend"),
        assistant_description="Generates executive summaries, cost attribution, and analytics.",
        search_terms=("reports", "analytics", "cost", "spending", "charts"),
        documentation_references=("docs/reports.md",),
        supported_operations=(
            OperationType.READ,
            OperationType.QUERY,
            OperationType.CREATE,
            OperationType.EXECUTE,
        ),
        tags=("reports", "analytics", "cost"),
    ),
    Capability(
        name="eaip.marketplace",
        title="Skill Marketplace",
        description="Discover, verify, and install validated tools and skills.",
        version="1.0.0",
        status=CapabilityStatus.ENABLED,
        capability_id="marketplace",
        category=CapabilityCategory.COLLABORATION,
        domain="eaip",
        owner="ecosystem",
        lifecycle_state="active",
        routes=("/marketplace",),
        navigation_references=("nav.marketplace",),
        api_operations=("GET /api/v1/marketplace/skills", "POST /api/v1/marketplace/install"),
        events=("skill.installed", "skill.uninstalled"),
        entities=("MarketplaceSkill", "PluginPackage"),
        assistant_description="Ecosystem marketplace for installing audited skills and integrations.",
        tour_metadata={"step_id": "marketplace", "order": "8"},
        search_terms=("marketplace", "skills", "plugins", "tools", "integrations"),
        documentation_references=("docs/marketplace.md",),
        supported_operations=(
            OperationType.READ,
            OperationType.QUERY,
            OperationType.CREATE,
            OperationType.EXECUTE,
        ),
        tags=("marketplace", "plugins", "ecosystem"),
    ),
    Capability(
        name="eaip.investigations",
        title="Investigations & Audit",
        description="Incident root-cause analysis, forensic audit trails, and timeline reconstruction.",
        version="1.0.0",
        status=CapabilityStatus.ENABLED,
        capability_id="investigations",
        category=CapabilityCategory.GOVERNANCE,
        domain="eaip",
        owner="audit-team",
        lifecycle_state="active",
        routes=("/investigations", "/activity"),
        navigation_references=("nav.activity",),
        api_operations=("GET /api/v1/investigations", "GET /api/v1/audit/logs"),
        events=("investigation.opened", "investigation.resolved", "audit.entry_created"),
        entities=("Investigation", "AuditTrailEntry", "TimelineEvent"),
        assistant_description="Correlates audit logs and anomalies to explain why events occurred.",
        tour_metadata={"step_id": "activity", "order": "6"},
        search_terms=("investigations", "audit", "activity", "logs", "forensics"),
        documentation_references=("docs/investigations.md",),
        related_capabilities=("eaip.monitoring", "eaip.administration"),
        supported_operations=(OperationType.READ, OperationType.QUERY, OperationType.CREATE),
        tags=("investigations", "audit", "governance", "security"),
    ),
    Capability(
        name="eaip.orchestration",
        title="Workforce Orchestration",
        description="Multi-agent collaboration plans, delegation networks, and human-in-the-loop approvals.",
        version="1.0.0",
        status=CapabilityStatus.ENABLED,
        capability_id="orchestration",
        category=CapabilityCategory.INTELLIGENCE,
        domain="eaip",
        owner="orchestration-team",
        lifecycle_state="active",
        routes=("/orchestrations",),
        navigation_references=("nav.orchestrations",),
        api_operations=("GET /api/v1/orchestrations", "POST /api/v1/orchestrations/plan"),
        events=("orchestration.planned", "orchestration.step_approved"),
        entities=("OrchestrationPlan", "ApprovalRequest", "DelegationGraph"),
        assistant_description="Coordinates complex multi-agent workflows with safety approval gates.",
        search_terms=("orchestration", "workforce", "coordination", "plans", "approvals"),
        documentation_references=("docs/orchestration.md",),
        related_capabilities=("eaip.agents", "eaip.missions", "eaip.workflows"),
        supported_operations=(
            OperationType.READ,
            OperationType.QUERY,
            OperationType.CREATE,
            OperationType.EXECUTE,
            OperationType.APPROVE,
        ),
        tags=("orchestration", "workforce", "governance"),
    ),
    Capability(
        name="eaip.guided_tour",
        title="Guided Tour",
        description="Interactive multi-step guided tour experience through platform capabilities.",
        version="1.0.0",
        status=CapabilityStatus.ENABLED,
        capability_id="guided_tour",
        category=CapabilityCategory.EXPERIENCE,
        domain="eaip",
        owner="ux-team",
        lifecycle_state="active",
        routes=(
            "/dashboard",
            "/agents",
            "/brains",
            "/knowledge",
            "/missions",
            "/monitoring",
            "/activity",
            "/administration",
            "/marketplace",
            "/memory",
        ),
        api_operations=(
            "GET /api/tour/preferences",
            "POST /api/tour/start",
            "POST /api/tour/{id}/command",
        ),
        events=("tour.started", "tour.step_advanced", "tour.completed", "tour.dismissed"),
        entities=("TourSession", "TourStep", "TourPreferences"),
        assistant_description="Interactive walkthrough of platform features with contextual voice narration.",
        search_terms=("tour", "walkthrough", "guide", "onboarding"),
        documentation_references=("docs/guided_tour.md",),
        supported_operations=(OperationType.READ, OperationType.EXECUTE),
        tags=("tour", "onboarding", "experience"),
    ),
    Capability(
        name="eaip.enterprise_assistant",
        title="Enterprise Assistant Interface",
        description="Spectral Personal Assistant launcher and interactive floating assistant surface.",
        version="1.0.0",
        status=CapabilityStatus.ENABLED,
        capability_id="enterprise_assistant",
        category=CapabilityCategory.EXPERIENCE,
        domain="eaip",
        owner="assistant-team",
        lifecycle_state="active",
        routes=("/dashboard",),
        api_operations=("GET /api/copilot/status",),
        events=("assistant.invoked", "assistant.mode_changed"),
        entities=("AssistantWidgetState", "AssistantVoiceState"),
        assistant_description="Interactive floating UI launcher and conversational panel.",
        search_terms=("assistant", "conductor", "copilot", "chat", "voice"),
        documentation_references=("docs/assistant.md",),
        related_capabilities=("eaip.conductor", "eaip.memory"),
        supported_operations=(OperationType.READ, OperationType.QUERY, OperationType.EXECUTE),
        tags=("assistant", "ui", "experience"),
    ),
    Capability(
        name="eaip.conductor",
        title="Conductor Copilot Engine",
        description="Governed platform copilot engine providing conversational queries and governed tool coordination.",
        version="1.0.0",
        status=CapabilityStatus.ENABLED,
        capability_id="conductor",
        category=CapabilityCategory.INTELLIGENCE,
        domain="eaip",
        owner="copilot-team",
        lifecycle_state="active",
        routes=("/dashboard",),
        api_operations=("POST /api/copilot/chat", "POST /api/copilot/action/approve"),
        events=("copilot.query_received", "copilot.tool_dispatched", "copilot.approval_requested"),
        entities=("CopilotSession", "CopilotMessage", "CopilotActionApproval"),
        assistant_description="Core governed reasoning and tool orchestration backend for the Conductor assistant.",
        search_terms=("conductor", "copilot", "reasoning", "ai assistant"),
        documentation_references=("docs/conductor.md",),
        related_capabilities=("eaip.enterprise_assistant", "eaip.agents", "eaip.memory"),
        supported_operations=(
            OperationType.READ,
            OperationType.QUERY,
            OperationType.EXECUTE,
            OperationType.APPROVE,
        ),
        tags=("conductor", "copilot", "intelligence", "governance"),
    ),
)


def load_canonical_inventory(registry: CapabilityRegistry | None = None) -> CapabilityRegistry:
    """Populate and return a CapabilityRegistry loaded with canonical EAIP capabilities.

    Args:
        registry: Existing registry to load into, or None to create a new one.

    Returns:
        CapabilityRegistry containing canonical capabilities.
    """
    target = registry if registry is not None else CapabilityRegistry()
    for cap in CANONICAL_CAPABILITIES:
        target.register(cap, replace=True)
    return target


__all__ = ["CANONICAL_CAPABILITIES", "load_canonical_inventory"]
