"""DocGenerator — generates OpenAPI specs and markdown documentation from endpoint registrations."""

from __future__ import annotations

from typing import Any

from eaip.apidocs.events import DocGenerated, EndpointDocRegistered
from eaip.apidocs.models import ApiDocConfig, EndpointDoc


class DocGenerator:
    def __init__(self, config: ApiDocConfig | None = None, event_bus: Any = None) -> None:
        self._config = config or ApiDocConfig(title="API", version="1.0.0")
        self._endpoints: dict[str, EndpointDoc] = {}
        self._event_bus = event_bus

    def register_endpoint_doc(self, endpoint: EndpointDoc) -> EndpointDoc:
        self._endpoints[endpoint.id] = endpoint
        if self._event_bus:
            self._event_bus.publish(
                EndpointDocRegistered(
                    endpoint_id=endpoint.id,
                    endpoint_path=endpoint.endpoint_path,
                    method=endpoint.method,
                )
            )
        return endpoint

    def get_endpoint_docs(self) -> list[EndpointDoc]:
        return list(self._endpoints.values())

    def remove_endpoint_doc(self, endpoint_id: str) -> None:
        self._endpoints.pop(endpoint_id, None)

    async def generate_openapi(self, spec_version: str = "3.0.3") -> dict[str, Any]:
        paths: dict[str, Any] = {}
        for ep in self._endpoints.values():
            method_lower = ep.method.lower()
            path_item = paths.setdefault(ep.endpoint_path, {})
            operation: dict[str, Any] = {
                "summary": ep.summary or ep.id,
                "description": ep.description or "",
                "parameters": [dict(p) for p in ep.parameters],
                "tags": list(ep.tags),
                "deprecated": ep.deprecated,
            }
            if ep.request_body:
                operation["requestBody"] = dict(ep.request_body)
            if ep.responses:
                operation["responses"] = {
                    str(k): dict(v) if isinstance(v, dict) else v for k, v in ep.responses.items()
                }
            else:
                operation["responses"] = {"200": {"description": "OK"}}
            path_item[method_lower] = operation

        spec: dict[str, Any] = {
            "openapi": spec_version,
            "info": {
                "title": self._config.title,
                "version": self._config.version,
                "description": self._config.description,
            },
            "paths": paths,
        }
        if self._config.contact:
            spec["info"]["contact"] = dict(self._config.contact)
        if self._config.license:
            spec["info"]["license"] = dict(self._config.license)
        if self._config.servers:
            spec["servers"] = [dict(s) for s in self._config.servers]

        if self._event_bus:
            self._event_bus.publish(
                DocGenerated(
                    doc_id=f"openapi_{spec_version}",
                    source_version=self._config.version,
                    format="openapi_json",
                )
            )
        return spec

    async def generate_markdown(self) -> str:
        lines: list[str] = []
        lines.append(f"# {self._config.title}")
        lines.append("")
        if self._config.description:
            lines.append(self._config.description)
            lines.append("")
        lines.append(f"**Version:** {self._config.version}")
        lines.append("")
        lines.append("## Endpoints")
        lines.append("")

        for ep in sorted(self._endpoints.values(), key=lambda e: (e.endpoint_path, e.method)):
            deprecated_tag = " *(deprecated)*" if ep.deprecated else ""
            lines.append(f"### `{ep.method.upper()}` {ep.endpoint_path}{deprecated_tag}")
            if ep.summary:
                lines.append(f"**{ep.summary}**")
            if ep.description:
                lines.append("")
                lines.append(ep.description)
            lines.append("")
            if ep.parameters:
                lines.append("**Parameters:**")
                for p in ep.parameters:
                    p_name = p.get("name", "?")
                    p_in = p.get("in", "?")
                    p_required = p.get("required", False)
                    req_mark = " (required)" if p_required else ""
                    lines.append(f"- `{p_name}` ({p_in}){req_mark}")
                lines.append("")

        lines.append("---")
        lines.append(f"*Generated by EAIP API Docs Generator v{self._config.version}*")
        return "\n".join(lines)


__all__ = ["DocGenerator"]
