"""Audit Enhancements — correlation, enrichment, aggregation, alerts, and streaming."""

from __future__ import annotations

from eaip.audit_enhancements.events import (
    AuditAggregationCompleted,
    AuditAlertResolved,
    AuditAlertTriggered,
    AuditCorrelationDetected,
    AuditCorrelationRuleCreated,
    AuditCorrelationRuleDeleted,
    AuditCorrelationRuleUpdated,
    AuditEnhancementConfigUpdated,
    AuditEnrichmentApplied,
    AuditEnrichmentRuleCreated,
    AuditReportGenerated,
    AuditStreamConfigured,
    AuditStreamStarted,
    AuditStreamStopped,
)
from eaip.audit_enhancements.exceptions import (
    AuditAggregationError,
    AuditAlertError,
    AuditCorrelationError,
    AuditEnhancementConfigError,
    AuditEnhancementError,
    AuditEnrichmentError,
    AuditReportError,
    AuditStreamError,
)
from eaip.audit_enhancements.health import AuditEnhancementHealthCheck
from eaip.audit_enhancements.integration import AuditEnhancementRuntimeModule
from eaip.audit_enhancements.models import (
    AuditAggregationResult,
    AuditAggregationRule,
    AuditAlertRule,
    AuditAlertSeverity,
    AuditCorrelationResult,
    AuditCorrelationRule,
    AuditEnhancementConfig,
    AuditEnhancementReport,
    AuditEnrichmentResult,
    AuditEnrichmentRule,
    AuditNotificationTarget,
    AuditRetentionRule,
    AuditStreamConfig,
    EnhancementType,
)
from eaip.audit_enhancements.service import AuditEnhancementService

__all__ = [
    "AuditAggregationCompleted",
    "AuditAggregationError",
    "AuditAggregationResult",
    "AuditAggregationRule",
    "AuditAlertError",
    "AuditAlertResolved",
    "AuditAlertRule",
    "AuditAlertSeverity",
    "AuditAlertTriggered",
    "AuditCorrelationDetected",
    "AuditCorrelationError",
    "AuditCorrelationResult",
    "AuditCorrelationRule",
    "AuditCorrelationRuleCreated",
    "AuditCorrelationRuleDeleted",
    "AuditCorrelationRuleUpdated",
    "AuditEnhancementConfig",
    "AuditEnhancementConfigError",
    "AuditEnhancementConfigUpdated",
    "AuditEnhancementError",
    "AuditEnhancementHealthCheck",
    "AuditEnhancementReport",
    "AuditEnhancementRuntimeModule",
    "AuditEnhancementService",
    "AuditEnrichmentApplied",
    "AuditEnrichmentError",
    "AuditEnrichmentResult",
    "AuditEnrichmentRule",
    "AuditEnrichmentRuleCreated",
    "AuditNotificationTarget",
    "AuditReportError",
    "AuditReportGenerated",
    "AuditRetentionRule",
    "AuditStreamConfig",
    "AuditStreamConfigured",
    "AuditStreamError",
    "AuditStreamStarted",
    "AuditStreamStopped",
    "EnhancementType",
]
