"""Organization management — structure, members, policies, domains, and reporting."""

from __future__ import annotations

from eaip.organization.events import (
    OrganizationActivated,
    OrganizationArchived,
    OrganizationAuditLogged,
    OrganizationCreated,
    OrganizationDeactivated,
    OrganizationDeleted,
    OrganizationDomainsVerified,
    OrganizationMemberAdded,
    OrganizationMemberRemoved,
    OrganizationMemberRoleChanged,
    OrganizationPolicyCreated,
    OrganizationPolicyUpdated,
    OrganizationReportGenerated,
    OrganizationSettingsUpdated,
    OrganizationSubscriptionsUpdated,
    OrganizationUnitAdded,
    OrganizationUnitMoved,
    OrganizationUnitRemoved,
    OrganizationUpdated,
)
from eaip.organization.exceptions import (
    OrganizationConfigError,
    OrganizationDomainError,
    OrganizationError,
    OrganizationMemberError,
    OrganizationNotFoundError,
    OrganizationPolicyError,
    OrganizationSubscriptionError,
    OrganizationUnitError,
)
from eaip.organization.health import OrganizationHealthCheck
from eaip.organization.integration import OrganizationRuntimeModule
from eaip.organization.models import (
    Organization,
    OrganizationAuditEntry,
    OrganizationConfig,
    OrganizationContact,
    OrganizationDomain,
    OrganizationFeature,
    OrganizationHierarchy,
    OrganizationMember,
    OrganizationPolicy,
    OrganizationReport,
    OrganizationRole,
    OrganizationSettings,
    OrganizationStatus,
    OrganizationSubscription,
    OrganizationType,
    OrganizationUnit,
    OrganizationUnitType,
)
from eaip.organization.service import OrganizationService

__all__ = [
    "Organization",
    "OrganizationActivated",
    "OrganizationArchived",
    "OrganizationAuditEntry",
    "OrganizationAuditLogged",
    "OrganizationConfig",
    "OrganizationConfigError",
    "OrganizationContact",
    "OrganizationCreated",
    "OrganizationDeactivated",
    "OrganizationDeleted",
    "OrganizationDomain",
    "OrganizationDomainError",
    "OrganizationDomainsVerified",
    "OrganizationError",
    "OrganizationFeature",
    "OrganizationHealthCheck",
    "OrganizationHierarchy",
    "OrganizationMember",
    "OrganizationMemberAdded",
    "OrganizationMemberError",
    "OrganizationMemberRemoved",
    "OrganizationMemberRoleChanged",
    "OrganizationNotFoundError",
    "OrganizationPolicy",
    "OrganizationPolicyCreated",
    "OrganizationPolicyError",
    "OrganizationPolicyUpdated",
    "OrganizationReport",
    "OrganizationReportGenerated",
    "OrganizationRole",
    "OrganizationRuntimeModule",
    "OrganizationService",
    "OrganizationSettings",
    "OrganizationSettingsUpdated",
    "OrganizationStatus",
    "OrganizationSubscription",
    "OrganizationSubscriptionError",
    "OrganizationSubscriptionsUpdated",
    "OrganizationType",
    "OrganizationUnit",
    "OrganizationUnitAdded",
    "OrganizationUnitError",
    "OrganizationUnitMoved",
    "OrganizationUnitRemoved",
    "OrganizationUnitType",
    "OrganizationUpdated",
]
