"""Search Analytics — query logging, metrics, reports, trends, alerts, funnels, dashboards."""

from eaip.search_analytics.events import (
    SearchAbandonmentAnalysisCompleted,
    SearchAnalyticsAlertTriggered,
    SearchAnalyticsConfigUpdated,
    SearchAnalyticsDashboardCreated,
    SearchAnalyticsDashboardUpdated,
    SearchAnalyticsReportGenerated,
    SearchClickThroughLogged,
    SearchFunnelAnalysisCompleted,
    SearchMetricsCollected,
    SearchPerformanceReportGenerated,
    SearchPopularQueryIdentified,
    SearchQueryLogged,
    SearchSessionAbandoned,
    SearchSessionCompleted,
    SearchSessionStarted,
    SearchTrendComputed,
    SearchZeroResultQueryIdentified,
)
from eaip.search_analytics.exceptions import (
    SearchAnalyticsAlertError,
    SearchAnalyticsConfigError,
    SearchAnalyticsDashboardError,
    SearchAnalyticsError,
    SearchAnalyticsQueryError,
    SearchAnalyticsReportError,
    SearchMetricsCollectionError,
)
from eaip.search_analytics.health import SearchAnalyticsHealthCheck
from eaip.search_analytics.integration import SearchAnalyticsRuntimeModule
from eaip.search_analytics.models import (
    SearchAbandonmentAnalysis,
    SearchAnalyticsAlert,
    SearchAnalyticsConfig,
    SearchAnalyticsDashboard,
    SearchAnalyticsReport,
    SearchClickThrough,
    SearchFunnel,
    SearchFunnelAnalysis,
    SearchFunnelStep,
    SearchMetrics,
    SearchMetricsPeriod,
    SearchPerformanceReport,
    SearchPopularQuery,
    SearchQueryLog,
    SearchSession,
    SearchSessionStatus,
    SearchTrend,
    SearchTrendPeriod,
    SearchZeroResultQuery,
)
from eaip.search_analytics.service import SearchAnalyticsService

__all__ = [
    "SearchAbandonmentAnalysis",
    "SearchAbandonmentAnalysisCompleted",
    "SearchAnalyticsAlert",
    "SearchAnalyticsAlertError",
    "SearchAnalyticsAlertTriggered",
    "SearchAnalyticsConfig",
    "SearchAnalyticsConfigError",
    "SearchAnalyticsConfigUpdated",
    "SearchAnalyticsDashboard",
    "SearchAnalyticsDashboardCreated",
    "SearchAnalyticsDashboardError",
    "SearchAnalyticsDashboardUpdated",
    "SearchAnalyticsError",
    "SearchAnalyticsHealthCheck",
    "SearchAnalyticsQueryError",
    "SearchAnalyticsReport",
    "SearchAnalyticsReportError",
    "SearchAnalyticsReportGenerated",
    "SearchAnalyticsRuntimeModule",
    "SearchAnalyticsService",
    "SearchClickThrough",
    "SearchClickThroughLogged",
    "SearchFunnel",
    "SearchFunnelAnalysis",
    "SearchFunnelAnalysisCompleted",
    "SearchFunnelStep",
    "SearchMetrics",
    "SearchMetricsCollected",
    "SearchMetricsCollectionError",
    "SearchMetricsPeriod",
    "SearchPerformanceReport",
    "SearchPerformanceReportGenerated",
    "SearchPopularQuery",
    "SearchPopularQueryIdentified",
    "SearchQueryLog",
    "SearchQueryLogged",
    "SearchSession",
    "SearchSessionAbandoned",
    "SearchSessionCompleted",
    "SearchSessionStarted",
    "SearchSessionStatus",
    "SearchTrend",
    "SearchTrendComputed",
    "SearchTrendPeriod",
    "SearchZeroResultQuery",
    "SearchZeroResultQueryIdentified",
]
