"""Knowledge Permissions — access control, roles, ACLs, and audit for knowledge resources.

EP-0215: Fine-grained permission management for knowledge collections,
documents, and retrieval operations.
"""

from __future__ import annotations

from eaip.knowledge_permissions.events import (
    KnowledgeAccessDenied,
    KnowledgeAccessGranted,
    KnowledgeAccessRuleCreated,
    KnowledgeAccessRuleEvaluated,
    KnowledgePermissionAuditLogged,
    KnowledgePermissionCreated,
    KnowledgePermissionDeleted,
    KnowledgePermissionGranted,
    KnowledgePermissionPolicyUpdated,
    KnowledgePermissionReportGenerated,
    KnowledgePermissionRevoked,
    KnowledgePermissionUpdated,
    KnowledgeRoleAssigned,
    KnowledgeRoleCreated,
    KnowledgeRoleDeleted,
    KnowledgeRoleUnassigned,
    KnowledgeRoleUpdated,
)
from eaip.knowledge_permissions.exceptions import (
    KnowledgePermissionError,
    PermissionAssignmentError,
    PermissionAuditError,
    PermissionConfigError,
    PermissionDeniedError,
    PermissionEvaluationError,
    PermissionNotFoundError,
    PermissionRoleError,
)
from eaip.knowledge_permissions.health import KnowledgePermissionHealthCheck
from eaip.knowledge_permissions.integration import KnowledgePermissionRuntimeModule
from eaip.knowledge_permissions.models import (
    AccessControlList,
    KnowledgeAccessAuditEntry,
    KnowledgeAccessRule,
    KnowledgeAccessScope,
    KnowledgePermission,
    KnowledgePermissionCondition,
    KnowledgePermissionConditionOperator,
    KnowledgePermissionConfig,
    KnowledgePermissionEvaluation,
    KnowledgePermissionPolicy,
    KnowledgePermissionReport,
    KnowledgeResourceAccess,
    KnowledgeResourcePermission,
    KnowledgeRole,
    KnowledgeRoleAssignment,
    PermissionLevel,
)
from eaip.knowledge_permissions.service import KnowledgePermissionService

__all__ = [
    "AccessControlList",
    "KnowledgeAccessAuditEntry",
    "KnowledgeAccessDenied",
    "KnowledgeAccessGranted",
    "KnowledgeAccessRule",
    "KnowledgeAccessRuleCreated",
    "KnowledgeAccessRuleEvaluated",
    "KnowledgeAccessScope",
    "KnowledgePermission",
    "KnowledgePermissionAuditLogged",
    "KnowledgePermissionCondition",
    "KnowledgePermissionConditionOperator",
    "KnowledgePermissionConfig",
    "KnowledgePermissionCreated",
    "KnowledgePermissionDeleted",
    "KnowledgePermissionError",
    "KnowledgePermissionEvaluation",
    "KnowledgePermissionGranted",
    "KnowledgePermissionHealthCheck",
    "KnowledgePermissionPolicy",
    "KnowledgePermissionPolicyUpdated",
    "KnowledgePermissionReport",
    "KnowledgePermissionReportGenerated",
    "KnowledgePermissionRevoked",
    "KnowledgePermissionRuntimeModule",
    "KnowledgePermissionService",
    "KnowledgePermissionUpdated",
    "KnowledgeResourceAccess",
    "KnowledgeResourcePermission",
    "KnowledgeRole",
    "KnowledgeRoleAssigned",
    "KnowledgeRoleAssignment",
    "KnowledgeRoleCreated",
    "KnowledgeRoleDeleted",
    "KnowledgeRoleUnassigned",
    "KnowledgeRoleUpdated",
    "PermissionAssignmentError",
    "PermissionAuditError",
    "PermissionConfigError",
    "PermissionDeniedError",
    "PermissionEvaluationError",
    "PermissionLevel",
    "PermissionNotFoundError",
    "PermissionRoleError",
]
