"""Model Fallback — EP-0208: fallback chains, graceful degradation, failover orchestration."""

from __future__ import annotations

from eaip.model_fallback.events import (
    DegradationLevelChanged,
    FallbackChainExecuted,
    FallbackConfigCreated,
    FallbackConfigDeleted,
    FallbackConfigUpdated,
    FallbackExecutionCompleted,
    FallbackExecutionFailed,
    FallbackHistoryLogged,
    FallbackMetricsCollected,
    FallbackRecoveryFailed,
    FallbackRecoverySucceeded,
    FallbackStepCompleted,
    FallbackStepFailed,
    FallbackStepSkipped,
    FallbackStepStarted,
    FallbackTriggered,
)
from eaip.model_fallback.exceptions import (
    DegradationError,
    FallbackChainError,
    FallbackConfigError,
    FallbackExecutionError,
    FallbackStepError,
    FallbackTriggerError,
    ModelFallbackError,
)
from eaip.model_fallback.health import ModelFallbackHealthCheck
from eaip.model_fallback.integration import ModelFallbackRuntimeModule
from eaip.model_fallback.models import (
    DegradationLevel,
    FallbackCondition,
    FallbackConfig,
    FallbackExecution,
    FallbackExecutionStatus,
    FallbackHealthStatus,
    FallbackHistoryEntry,
    FallbackMetrics,
    FallbackPolicy,
    FallbackResult,
    FallbackStep,
    FallbackStepStatus,
    FallbackStrategy,
    FallbackTrigger,
    GracefulDegradationConfig,
    ModelFallbackChain,
)
from eaip.model_fallback.service import ModelFallbackService

__all__ = [
    "DegradationError",
    "DegradationLevel",
    "DegradationLevelChanged",
    "FallbackChainError",
    "FallbackChainExecuted",
    "FallbackCondition",
    "FallbackConfig",
    "FallbackConfigCreated",
    "FallbackConfigDeleted",
    "FallbackConfigError",
    "FallbackConfigUpdated",
    "FallbackExecution",
    "FallbackExecutionCompleted",
    "FallbackExecutionError",
    "FallbackExecutionFailed",
    "FallbackExecutionStatus",
    "FallbackHealthStatus",
    "FallbackHistoryEntry",
    "FallbackHistoryLogged",
    "FallbackMetrics",
    "FallbackMetricsCollected",
    "FallbackPolicy",
    "FallbackRecoveryFailed",
    "FallbackRecoverySucceeded",
    "FallbackResult",
    "FallbackStep",
    "FallbackStepCompleted",
    "FallbackStepError",
    "FallbackStepFailed",
    "FallbackStepSkipped",
    "FallbackStepStarted",
    "FallbackStepStatus",
    "FallbackStrategy",
    "FallbackTrigger",
    "FallbackTriggerError",
    "FallbackTriggered",
    "GracefulDegradationConfig",
    "ModelFallbackChain",
    "ModelFallbackError",
    "ModelFallbackHealthCheck",
    "ModelFallbackRuntimeModule",
    "ModelFallbackService",
]
