"""Data models for Recommendations."""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from eaip.shared.time import utc_now


class RecommendationStatus(StrEnum):
    PENDING = "pending"
    APPLIED = "applied"
    DISMISSED = "dismissed"


class Recommendation(BaseModel):
    """A recommendation generated by the system."""
    model_config = ConfigDict(frozen=True, extra="forbid")

    id: str
    tenant_id: str
    title: str
    description: str
    score: float
    metadata: dict[str, Any] = Field(default_factory=dict)
    status: RecommendationStatus = Field(default=RecommendationStatus.PENDING)
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)


__all__ = ["Recommendation", "RecommendationStatus"]
