"""Resource Optimization — analyze, recommend, and execute resource optimization actions."""

from __future__ import annotations

from eaip.resource_optimization.events import (
    ResourceActionCompleted,
    ResourceActionFailed,
    ResourceActionStarted,
    ResourceAllocationAdjusted,
    ResourceConstraintDetected,
    ResourceDemandForecastComputed,
    ResourceMetricsCollected,
    ResourceOptimizationConfigUpdated,
    ResourceOptimizationDashboardUpdated,
    ResourceOptimizationReportGenerated,
    ResourceOptimizationRuleCreated,
    ResourceOptimizationRuleDeleted,
    ResourceOptimizationRuleUpdated,
    ResourceRecommendationApplied,
    ResourceRecommendationDismissed,
    ResourceRecommendationGenerated,
    ResourceUtilizationAnalyzed,
)
from eaip.resource_optimization.exceptions import (
    ResourceActionError,
    ResourceAllocationError,
    ResourceConstraintError,
    ResourceDemandForecastError,
    ResourceMetricsError,
    ResourceOptimizationConfigError,
    ResourceOptimizationError,
    ResourceRecommendationError,
)
from eaip.resource_optimization.health import ResourceOptimizationHealthCheck
from eaip.resource_optimization.integration import ResourceOptimizationRuntimeModule
from eaip.resource_optimization.models import (
    OptimizationStrategy,
    RecommendationPriority,
    ResourceAction,
    ResourceActionStatus,
    ResourceAllocation,
    ResourceConstraint,
    ResourceDemandForecast,
    ResourceMetrics,
    ResourceOptimizationConfig,
    ResourceOptimizationDashboard,
    ResourceOptimizationHistory,
    ResourceOptimizationReport,
    ResourceOptimizationRule,
    ResourceOptimizationSchedule,
    ResourceRecommendation,
    ResourceTag,
    ResourceType,
    ResourceUtilization,
)
from eaip.resource_optimization.service import ResourceOptimizationService

__all__ = [
    "OptimizationStrategy",
    "RecommendationPriority",
    "ResourceAction",
    "ResourceActionCompleted",
    "ResourceActionError",
    "ResourceActionFailed",
    "ResourceActionStarted",
    "ResourceActionStatus",
    "ResourceAllocation",
    "ResourceAllocationAdjusted",
    "ResourceAllocationError",
    "ResourceConstraint",
    "ResourceConstraintDetected",
    "ResourceConstraintError",
    "ResourceDemandForecast",
    "ResourceDemandForecastComputed",
    "ResourceDemandForecastError",
    "ResourceMetrics",
    "ResourceMetricsCollected",
    "ResourceMetricsError",
    "ResourceOptimizationConfig",
    "ResourceOptimizationConfigError",
    "ResourceOptimizationConfigUpdated",
    "ResourceOptimizationDashboard",
    "ResourceOptimizationDashboardUpdated",
    "ResourceOptimizationError",
    "ResourceOptimizationHealthCheck",
    "ResourceOptimizationHistory",
    "ResourceOptimizationReport",
    "ResourceOptimizationReportGenerated",
    "ResourceOptimizationRule",
    "ResourceOptimizationRuleCreated",
    "ResourceOptimizationRuleDeleted",
    "ResourceOptimizationRuleUpdated",
    "ResourceOptimizationRuntimeModule",
    "ResourceOptimizationSchedule",
    "ResourceOptimizationService",
    "ResourceRecommendation",
    "ResourceRecommendationApplied",
    "ResourceRecommendationDismissed",
    "ResourceRecommendationError",
    "ResourceRecommendationGenerated",
    "ResourceTag",
    "ResourceType",
    "ResourceUtilization",
    "ResourceUtilizationAnalyzed",
]
