CONSULTANCY_PACK = {
    "pack_id": "consultancy",
    "industry": "consultancy",
    "name": "Consultancy Excellence",
    "description": "Strategy agent, engagement manager, knowledge manager, onboarding, delivery, SOW knowledge, utilization analytics.",
    "version": "1.0.0",
    "agents": ({"id": "cons-strategy", "name": "Strategy Agent", "description": "Strategic advisory"}, {"id": "cons-engagement", "name": "Engagement Manager", "description": "Client engagement orchestration"}),
    "workflows": ({"id": "cons-onboarding", "name": "Client Onboarding"}, {"id": "cons-delivery", "name": "Delivery Review"}),
    "missions": ({"id": "cons-delivery-mission", "name": "Delivery Excellence Mission"},),
    "knowledge_collections": ("cons-playbooks", "cons-cases"),
    "policies": ("cons-delivery-policy",),
    "dashboards": ("consultancy-ops",),
    "kpis": ({"name": "utilization_rate", "target": 75}, {"name": "client_satisfaction", "target": 90}),
    "simulation_scenarios": ("apex",),
    "marketplace_integrations": ("apex-crm", "apex-projects", "apex-docs"),
    "recommended_schedules": ({"name": "Weekly Utilization Review", "trigger": {"kind": "cron", "cron_expr": "0 9 * * 1"}},),
    "role_templates": ("partner", "consultant", "analyst"),
    "permissions": ("consultancy:read", "consultancy:write"),
    "metadata": {"industry": "consultancy", "synthetic": True},
}
