FINANCIAL_PACK = {
    "pack_id": "financial",
    "industry": "financial",
    "name": "Financial Services",
    "description": "Risk analyst, compliance agent, KYC/AML synthetic workflows, portfolio simulation, audit scenarios.",
    "version": "1.0.0",
    "agents": ({"id": "fin-risk", "name": "Risk Analyst", "description": "Portfolio and operational risk analysis"}, {"id": "fin-compliance", "name": "Compliance Agent", "description": "KYC/AML compliance"}),
    "workflows": ({"id": "fin-risk-review", "name": "Risk Review Workflow"}, {"id": "fin-kyc", "name": "KYC/AML Workflow"}),
    "missions": ({"id": "fin-audit-mission", "name": "Financial Audit Mission"},),
    "knowledge_collections": ("fin-policies", "fin-regulations"),
    "policies": ("fin-kyc-policy", "fin-risk-policy"),
    "dashboards": ("financial-ops",),
    "kpis": ({"name": "risk_score", "target": 80}, {"name": "kyc_completion", "target": 98}),
    "simulation_scenarios": ("financial",),
    "marketplace_integrations": ("apex-crm",),
    "recommended_schedules": ({"name": "Risk Batch", "trigger": {"kind": "interval", "interval_seconds": 86400}},),
    "role_templates": ("risk_analyst", "compliance_officer", "operations_manager"),
    "permissions": ("financial:read", "financial:write"),
    "metadata": {"industry": "financial", "synthetic": True},
}
