HEALTHCARE_PACK = {
    "pack_id": "healthcare",
    "industry": "healthcare",
    "name": "Healthcare Operations",
    "description": "Patient-operations coordinator, compliance agent, scheduling workflows, safety missions, policy knowledge, synthetic records, audit workflows.",
    "version": "1.0.0",
    "agents": ({"id": "hc-coordinator", "name": "Patient-Ops Coordinator", "description": "Coordinates patient operations and scheduling"}, {"id": "hc-compliance", "name": "Compliance Agent", "description": "Healthcare compliance checks"}),
    "workflows": ({"id": "hc-scheduling", "name": "Care Scheduling Workflow"}, {"id": "hc-audit", "name": "Safety Audit Workflow"}),
    "missions": ({"id": "hc-safety-mission", "name": "Patient Safety Mission"},),
    "knowledge_collections": ("hc-policies", "hc-protocols"),
    "policies": ("hc-hipaa-policy", "hc-safety-policy"),
    "dashboards": ("healthcare-ops",),
    "kpis": ({"name": "patient_wait_time", "target": 30}, {"name": "compliance_score", "target": 95}),
    "simulation_scenarios": ("meridian",),
    "marketplace_integrations": ("meridian-compliance", "meridian-scheduling", "meridian-records"),
    "recommended_schedules": ({"name": "Daily Compliance Check", "trigger": {"kind": "cron", "cron_expr": "0 9 * * *"}},),
    "role_templates": ("clinician", "compliance_officer", "scheduler"),
    "permissions": ("healthcare:read", "healthcare:write"),
    "metadata": {"industry": "healthcare", "synthetic": True},
}
