MANUFACTURING_PACK = {
    "pack_id": "manufacturing",
    "industry": "manufacturing",
    "name": "Manufacturing Operations",
    "description": "Production planner, quality engineer, supply-chain analyst, inventory, scheduling, quality incidents, supplier scenarios.",
    "version": "1.0.0",
    "agents": ({"id": "mfg-planner", "name": "Production Planner", "description": "Production scheduling and planning"}, {"id": "mfg-quality", "name": "Quality Engineer", "description": "Quality incidents and SPC"}),
    "workflows": ({"id": "mfg-production", "name": "Production Scheduling"}, {"id": "mfg-quality-incident", "name": "Quality Incident Workflow"}),
    "missions": ({"id": "mfg-ops-mission", "name": "Manufacturing Ops Mission"},),
    "knowledge_collections": ("mfg-sops", "mfg-suppliers"),
    "policies": ("mfg-quality-policy", "mfg-safety-policy"),
    "dashboards": ("manufacturing-ops",),
    "kpis": ({"name": "oee", "target": 85}, {"name": "defect_rate", "target": 2}),
    "simulation_scenarios": ("nova",),
    "marketplace_integrations": ("nova-erp", "nova-inventory", "nova-production"),
    "recommended_schedules": ({"name": "Shift Handover", "trigger": {"kind": "cron", "cron_expr": "0 6 * * *"}},),
    "role_templates": ("planner", "quality_engineer", "supply_analyst"),
    "permissions": ("manufacturing:read", "manufacturing:write"),
    "metadata": {"industry": "manufacturing", "synthetic": True},
}
