RETAIL_PACK = {
    "pack_id": "retail",
    "industry": "retail",
    "name": "D2C / Retail Growth",
    "description": "Growth analyst, merchandising, customer ops, campaign workflows, inventory, support, product analytics.",
    "version": "1.0.0",
    "agents": ({"id": "ret-growth", "name": "Growth Analyst", "description": "Demand and growth analysis"}, {"id": "ret-merch", "name": "Merchandising Agent", "description": "Assortment and pricing"}),
    "workflows": ({"id": "ret-campaign", "name": "Campaign Workflow"}, {"id": "ret-fulfillment", "name": "Fulfillment Workflow"}),
    "missions": ({"id": "ret-growth-mission", "name": "Growth Mission"},),
    "knowledge_collections": ("ret-catalog", "ret-support"),
    "policies": ("ret-returns-policy",),
    "dashboards": ("retail-ops",),
    "kpis": ({"name": "conversion_rate", "target": 3}, {"name": "fulfillment_sla", "target": 98}),
    "simulation_scenarios": ("retail",),
    "marketplace_integrations": ("apex-crm",),
    "recommended_schedules": ({"name": "Daily Demand Sync", "trigger": {"kind": "interval", "interval_seconds": 3600}},),
    "role_templates": ("growth_analyst", "merchandiser", "support_agent"),
    "permissions": ("retail:read", "retail:write"),
    "metadata": {"industry": "retail", "synthetic": True},
}
