"""Connector Management — register, configure, monitor, and operate external connectors."""

from __future__ import annotations

from eaip.connectors.events import (
    ConnectorActivated,
    ConnectorAuthRotated,
    ConnectorConfigUpdated,
    ConnectorDeactivated,
    ConnectorHealthCheckCompleted,
    ConnectorHealthStatusChanged,
    ConnectorMetricsCollected,
    ConnectorOperationExecuted,
    ConnectorOperationFailed,
    ConnectorRegistered,
    ConnectorSyncCompleted,
    ConnectorSyncFailed,
    ConnectorSyncStarted,
    ConnectorTested,
    ConnectorTestFailed,
    ConnectorTestPassed,
    ConnectorUnregistered,
    ConnectorUpdated,
)
from eaip.connectors.exceptions import (
    ConnectorAuthError,
    ConnectorConfigError,
    ConnectorConnectionError,
    ConnectorError,
    ConnectorHealthError,
    ConnectorNotFoundError,
    ConnectorOperationError,
    ConnectorRateLimitError,
    ConnectorSyncError,
)
from eaip.connectors.health import ConnectorHealthCheck
from eaip.connectors.integration import ConnectorRuntimeModule
from eaip.connectors.models import (
    AuthMethod,
    ConnectorAuthConfig,
    ConnectorConfig,
    ConnectorDefinition,
    ConnectorEndpoint,
    ConnectorHealthStatus,
    ConnectorMetadata,
    ConnectorMetrics,
    ConnectorOperation,
    ConnectorOperationType,
    ConnectorRateLimit,
    ConnectorRegistryEntry,
    ConnectorRetryPolicy,
    ConnectorSchema,
    ConnectorStatus,
    ConnectorSyncResult,
    ConnectorType,
)
from eaip.connectors.service import ConnectorService

__all__ = [
    "AuthMethod",
    "ConnectorActivated",
    "ConnectorAuthConfig",
    "ConnectorAuthError",
    "ConnectorAuthRotated",
    "ConnectorConfig",
    "ConnectorConfigError",
    "ConnectorConfigUpdated",
    "ConnectorConnectionError",
    "ConnectorDeactivated",
    "ConnectorDefinition",
    "ConnectorEndpoint",
    "ConnectorError",
    "ConnectorHealthCheck",
    "ConnectorHealthCheckCompleted",
    "ConnectorHealthError",
    "ConnectorHealthStatus",
    "ConnectorHealthStatusChanged",
    "ConnectorMetadata",
    "ConnectorMetrics",
    "ConnectorMetricsCollected",
    "ConnectorNotFoundError",
    "ConnectorOperation",
    "ConnectorOperationError",
    "ConnectorOperationExecuted",
    "ConnectorOperationFailed",
    "ConnectorOperationType",
    "ConnectorRateLimit",
    "ConnectorRateLimitError",
    "ConnectorRegistryEntry",
    "ConnectorRetryPolicy",
    "ConnectorRuntimeModule",
    "ConnectorSchema",
    "ConnectorService",
    "ConnectorStatus",
    "ConnectorSyncCompleted",
    "ConnectorSyncError",
    "ConnectorSyncFailed",
    "ConnectorSyncResult",
    "ConnectorSyncStarted",
    "ConnectorTestFailed",
    "ConnectorTestPassed",
    "ConnectorTested",
    "ConnectorType",
    "ConnectorUnregistered",
    "ConnectorUpdated",
]
