"""AI Governance & Compliance subsystem.

Combines EP-0202 (AI Governance) and EP-0203 (AI Compliance) into a single
package providing governance policies, compliance checks, audit trails,
reviews, risk assessment, bias detection, fairness metrics, and explainability.
"""

from __future__ import annotations

from eaip.ai_governance.events import (
    AiAuditTrailEntryCreated,
    AiBiasCheckCompleted,
    AiComplianceCheckCompleted,
    AiComplianceCheckFailed,
    AiComplianceCheckStarted,
    AiComplianceReportGenerated,
    AiComplianceRequirementUpdated,
    AiFairnessMetricComputed,
    AiGovernanceDashboardUpdated,
    AiGovernancePolicyCreated,
    AiGovernancePolicyEnforced,
    AiGovernancePolicyUpdated,
    AiGovernancePolicyViolated,
    AiGovernanceReviewApproved,
    AiGovernanceReviewCompleted,
    AiGovernanceReviewRejected,
    AiGovernanceReviewStarted,
    AiModelRiskAssessed,
)
from eaip.ai_governance.exceptions import (
    AiBiasDetectionError,
    AiComplianceCheckError,
    AiComplianceError,
    AiComplianceRequirementError,
    AiExplainabilityError,
    AiFairnessError,
    AiGovernanceError,
    AiGovernancePolicyError,
    AiGovernanceViolationError,
    AiReviewError,
    AiRiskAssessmentError,
)
from eaip.ai_governance.health import AiGovernanceHealthCheck
from eaip.ai_governance.integration import AiGovernanceRuntimeModule
from eaip.ai_governance.models import (
    AiAuditTrail,
    AiBiasCheckResult,
    AiComplianceCheck,
    AiComplianceReport,
    AiComplianceRequirement,
    AiComplianceResult,
    AiExplainabilityRecord,
    AiFairnessMetric,
    AiGovernanceConfig,
    AiGovernanceDashboard,
    AiGovernancePolicy,
    AiGovernanceReview,
    AiGovernanceRule,
    AiModelRiskAssessment,
    ComplianceStandard,
    ComplianceStatus,
    PolicyType,
    ReviewStatus,
    RiskLevel,
)
from eaip.ai_governance.service import AiGovernanceService

__all__ = [
    "AiAuditTrail",
    "AiAuditTrailEntryCreated",
    "AiBiasCheckCompleted",
    "AiBiasCheckResult",
    "AiBiasDetectionError",
    "AiComplianceCheck",
    "AiComplianceCheckCompleted",
    "AiComplianceCheckError",
    "AiComplianceCheckFailed",
    "AiComplianceCheckStarted",
    "AiComplianceError",
    "AiComplianceReport",
    "AiComplianceReportGenerated",
    "AiComplianceRequirement",
    "AiComplianceRequirementError",
    "AiComplianceRequirementUpdated",
    "AiComplianceResult",
    "AiExplainabilityError",
    "AiExplainabilityRecord",
    "AiFairnessError",
    "AiFairnessMetric",
    "AiFairnessMetricComputed",
    "AiGovernanceConfig",
    "AiGovernanceDashboard",
    "AiGovernanceDashboardUpdated",
    "AiGovernanceError",
    "AiGovernanceHealthCheck",
    "AiGovernancePolicy",
    "AiGovernancePolicyCreated",
    "AiGovernancePolicyEnforced",
    "AiGovernancePolicyError",
    "AiGovernancePolicyUpdated",
    "AiGovernancePolicyViolated",
    "AiGovernanceReview",
    "AiGovernanceReviewApproved",
    "AiGovernanceReviewCompleted",
    "AiGovernanceReviewRejected",
    "AiGovernanceReviewStarted",
    "AiGovernanceRule",
    "AiGovernanceRuntimeModule",
    "AiGovernanceService",
    "AiGovernanceViolationError",
    "AiModelRiskAssessed",
    "AiModelRiskAssessment",
    "AiReviewError",
    "AiRiskAssessmentError",
    "ComplianceStandard",
    "ComplianceStatus",
    "PolicyType",
    "ReviewStatus",
    "RiskLevel",
]
