"""Platform Lifecycle Management — manage the full lifecycle of an EAIP platform instance."""

from __future__ import annotations

from eaip.platform_lifecycle.events import (
    PlatformComponentStatusChanged,
    PlatformDeprecationNoticeIssued,
    PlatformHealthSummaryGenerated,
    PlatformLifecycleAuditLogged,
    PlatformLifecyclePhaseChanged,
    PlatformLifecyclePolicyApplied,
    PlatformLifecycleReportGenerated,
    PlatformLifecycleStateTransitioned,
    PlatformMaintenanceWindowEnded,
    PlatformMaintenanceWindowStarted,
    PlatformMigrationCompleted,
    PlatformMigrationFailed,
    PlatformMigrationRolledBack,
    PlatformMigrationStarted,
    PlatformUpgradeCompleted,
    PlatformUpgradeFailed,
    PlatformUpgradeRolledBack,
    PlatformUpgradeStarted,
    PlatformVersionUpdated,
)
from eaip.platform_lifecycle.exceptions import (
    PlatformComponentError,
    PlatformLifecycleConfigError,
    PlatformLifecycleError,
    PlatformLifecycleStateError,
    PlatformLifecycleTransitionError,
    PlatformMaintenanceError,
    PlatformMigrationError,
    PlatformUpgradeError,
)
from eaip.platform_lifecycle.health import PlatformLifecycleHealthCheck
from eaip.platform_lifecycle.integration import PlatformLifecycleRuntimeModule
from eaip.platform_lifecycle.models import (
    ComponentStatus,
    PlatformComponent,
    PlatformDeprecationNotice,
    PlatformHealthSummary,
    PlatformLifecycleAuditEntry,
    PlatformLifecycleConfig,
    PlatformLifecycleDashboard,
    PlatformLifecycleEvent,
    PlatformLifecyclePhase,
    PlatformLifecyclePolicy,
    PlatformLifecycleReport,
    PlatformLifecycleSchedule,
    PlatformLifecycleState,
    PlatformLifecycleTransition,
    PlatformMaintenanceWindow,
    PlatformMigration,
    PlatformMigrationStatus,
    PlatformUpgrade,
    PlatformUpgradeStatus,
    PlatformVersionInfo,
)
from eaip.platform_lifecycle.service import PlatformLifecycleService

__all__ = [
    "ComponentStatus",
    "PlatformComponent",
    "PlatformComponentError",
    "PlatformComponentStatusChanged",
    "PlatformDeprecationNotice",
    "PlatformDeprecationNoticeIssued",
    "PlatformHealthSummary",
    "PlatformHealthSummaryGenerated",
    "PlatformLifecycleAuditEntry",
    "PlatformLifecycleAuditLogged",
    "PlatformLifecycleConfig",
    "PlatformLifecycleConfigError",
    "PlatformLifecycleDashboard",
    "PlatformLifecycleError",
    "PlatformLifecycleEvent",
    "PlatformLifecycleHealthCheck",
    "PlatformLifecyclePhase",
    "PlatformLifecyclePhaseChanged",
    "PlatformLifecyclePolicy",
    "PlatformLifecyclePolicyApplied",
    "PlatformLifecycleReport",
    "PlatformLifecycleReportGenerated",
    "PlatformLifecycleRuntimeModule",
    "PlatformLifecycleSchedule",
    "PlatformLifecycleService",
    "PlatformLifecycleState",
    "PlatformLifecycleStateError",
    "PlatformLifecycleStateTransitioned",
    "PlatformLifecycleTransition",
    "PlatformLifecycleTransitionError",
    "PlatformMaintenanceError",
    "PlatformMaintenanceWindow",
    "PlatformMaintenanceWindowEnded",
    "PlatformMaintenanceWindowStarted",
    "PlatformMigration",
    "PlatformMigrationCompleted",
    "PlatformMigrationError",
    "PlatformMigrationFailed",
    "PlatformMigrationRolledBack",
    "PlatformMigrationStarted",
    "PlatformMigrationStatus",
    "PlatformUpgrade",
    "PlatformUpgradeCompleted",
    "PlatformUpgradeError",
    "PlatformUpgradeFailed",
    "PlatformUpgradeRolledBack",
    "PlatformUpgradeStarted",
    "PlatformUpgradeStatus",
    "PlatformVersionInfo",
    "PlatformVersionUpdated",
]
