"""Enterprise-wide settings — categories, groups, definitions, profiles, validation, and audit."""

from __future__ import annotations

from eaip.enterprise_settings.events import (
    EnterpriseSettingsAuditLogged,
    EnterpriseSettingsCategoryCreated,
    EnterpriseSettingsCategoryDeleted,
    EnterpriseSettingsCategoryUpdated,
    EnterpriseSettingsCreated,
    EnterpriseSettingsDeleted,
    EnterpriseSettingsEnvironmentOverrideSet,
    EnterpriseSettingsExported,
    EnterpriseSettingsGroupCreated,
    EnterpriseSettingsGroupDeleted,
    EnterpriseSettingsGroupUpdated,
    EnterpriseSettingsHistoryRecorded,
    EnterpriseSettingsImported,
    EnterpriseSettingsProfileActivated,
    EnterpriseSettingsProfileDeactivated,
    EnterpriseSettingsTemplateApplied,
    EnterpriseSettingsUpdated,
    EnterpriseSettingsValidated,
)
from eaip.enterprise_settings.exceptions import (
    EnterpriseSettingsCategoryError,
    EnterpriseSettingsError,
    EnterpriseSettingsExportError,
    EnterpriseSettingsImportError,
    EnterpriseSettingsNotFoundError,
    EnterpriseSettingsPermissionError,
    EnterpriseSettingsProfileError,
    EnterpriseSettingsValidationError,
)
from eaip.enterprise_settings.health import EnterpriseSettingsHealthCheck
from eaip.enterprise_settings.integration import EnterpriseSettingsRuntimeModule
from eaip.enterprise_settings.models import (
    EnterpriseSettings,
    SettingsAuditEntry,
    SettingsCategory,
    SettingsConfig,
    SettingsDefinition,
    SettingsEnvironmentOverride,
    SettingsExport,
    SettingsGroup,
    SettingsHistoryEntry,
    SettingsImport,
    SettingsNotification,
    SettingsPermission,
    SettingsProfile,
    SettingsScope,
    SettingsTemplate,
    SettingsValidation,
    SettingsValidationResult,
    SettingsValue,
)
from eaip.enterprise_settings.service import EnterpriseSettingsService

__all__ = [
    "EnterpriseSettings",
    "EnterpriseSettingsAuditLogged",
    "EnterpriseSettingsCategoryCreated",
    "EnterpriseSettingsCategoryDeleted",
    "EnterpriseSettingsCategoryError",
    "EnterpriseSettingsCategoryUpdated",
    "EnterpriseSettingsCreated",
    "EnterpriseSettingsDeleted",
    "EnterpriseSettingsEnvironmentOverrideSet",
    "EnterpriseSettingsError",
    "EnterpriseSettingsExportError",
    "EnterpriseSettingsExported",
    "EnterpriseSettingsGroupCreated",
    "EnterpriseSettingsGroupDeleted",
    "EnterpriseSettingsGroupUpdated",
    "EnterpriseSettingsHealthCheck",
    "EnterpriseSettingsHistoryRecorded",
    "EnterpriseSettingsImportError",
    "EnterpriseSettingsImported",
    "EnterpriseSettingsNotFoundError",
    "EnterpriseSettingsPermissionError",
    "EnterpriseSettingsProfileActivated",
    "EnterpriseSettingsProfileDeactivated",
    "EnterpriseSettingsProfileError",
    "EnterpriseSettingsRuntimeModule",
    "EnterpriseSettingsService",
    "EnterpriseSettingsTemplateApplied",
    "EnterpriseSettingsUpdated",
    "EnterpriseSettingsValidated",
    "EnterpriseSettingsValidationError",
    "SettingsAuditEntry",
    "SettingsCategory",
    "SettingsConfig",
    "SettingsDefinition",
    "SettingsEnvironmentOverride",
    "SettingsExport",
    "SettingsGroup",
    "SettingsHistoryEntry",
    "SettingsImport",
    "SettingsNotification",
    "SettingsPermission",
    "SettingsProfile",
    "SettingsScope",
    "SettingsTemplate",
    "SettingsValidation",
    "SettingsValidationResult",
    "SettingsValue",
]
