"""Department Management — organizational structure, budgets, resources, and reports."""

from __future__ import annotations

from eaip.department_management.events import (
    DepartmentActivated,
    DepartmentAuditLogged,
    DepartmentBudgetUpdated,
    DepartmentCreated,
    DepartmentDeactivated,
    DepartmentDeleted,
    DepartmentHierarchyChanged,
    DepartmentMemberAdded,
    DepartmentMemberRemoved,
    DepartmentMemberRoleChanged,
    DepartmentMerged,
    DepartmentReportGenerated,
    DepartmentResourceAllocated,
    DepartmentResourceReleased,
    DepartmentSettingsUpdated,
    DepartmentSplit,
    DepartmentUpdated,
)
from eaip.department_management.exceptions import (
    DepartmentBudgetError,
    DepartmentConfigError,
    DepartmentError,
    DepartmentHierarchyError,
    DepartmentMemberError,
    DepartmentNotFoundError,
    DepartmentResourceError,
)
from eaip.department_management.health import DepartmentManagementHealthCheck
from eaip.department_management.integration import DepartmentManagementRuntimeModule
from eaip.department_management.models import (
    Department,
    DepartmentAuditEntry,
    DepartmentBudget,
    DepartmentCategory,
    DepartmentConfig,
    DepartmentContact,
    DepartmentHierarchy,
    DepartmentMember,
    DepartmentPolicy,
    DepartmentReport,
    DepartmentResource,
    DepartmentResourceType,
    DepartmentRole,
    DepartmentSettings,
    DepartmentStatus,
)
from eaip.department_management.service import DepartmentManagementService

__all__ = [
    "Department",
    "DepartmentActivated",
    "DepartmentAuditEntry",
    "DepartmentAuditLogged",
    "DepartmentBudget",
    "DepartmentBudgetError",
    "DepartmentBudgetUpdated",
    "DepartmentCategory",
    "DepartmentConfig",
    "DepartmentConfigError",
    "DepartmentContact",
    "DepartmentCreated",
    "DepartmentDeactivated",
    "DepartmentDeleted",
    "DepartmentError",
    "DepartmentHierarchy",
    "DepartmentHierarchyChanged",
    "DepartmentHierarchyError",
    "DepartmentManagementHealthCheck",
    "DepartmentManagementRuntimeModule",
    "DepartmentManagementService",
    "DepartmentMember",
    "DepartmentMemberAdded",
    "DepartmentMemberError",
    "DepartmentMemberRemoved",
    "DepartmentMemberRoleChanged",
    "DepartmentMerged",
    "DepartmentNotFoundError",
    "DepartmentPolicy",
    "DepartmentReport",
    "DepartmentReportGenerated",
    "DepartmentResource",
    "DepartmentResourceAllocated",
    "DepartmentResourceError",
    "DepartmentResourceReleased",
    "DepartmentResourceType",
    "DepartmentRole",
    "DepartmentSettings",
    "DepartmentSettingsUpdated",
    "DepartmentSplit",
    "DepartmentStatus",
    "DepartmentUpdated",
]
