"""AI Cost Optimization — tracking, budgets, alerts, optimization, projections, allocations."""

from __future__ import annotations

from eaip.ai_cost.events import (
    AiCostAllocationUpdated,
    AiCostAnomalyDetected,
    AiCostBudgetAlertTriggered,
    AiCostBudgetCreated,
    AiCostBudgetExceeded,
    AiCostBudgetUpdated,
    AiCostDashboardUpdated,
    AiCostOptimizationApplied,
    AiCostOptimizationRuleCreated,
    AiCostProjectionComputed,
    AiCostRecorded,
    AiCostReportGenerated,
    ModelCostRateUpdated,
)
from eaip.ai_cost.exceptions import (
    AiCostAllocationError,
    AiCostAnomalyError,
    AiCostBudgetError,
    AiCostError,
    AiCostOptimizationError,
    AiCostRecordError,
    AiCostReportError,
)
from eaip.ai_cost.health import AiCostHealthCheck
from eaip.ai_cost.integration import AiCostRuntimeModule
from eaip.ai_cost.models import (
    AiCostAlert,
    AiCostAllocation,
    AiCostBudget,
    AiCostConfig,
    AiCostDashboard,
    AiCostOptimizationRule,
    AiCostProjection,
    AiCostRecord,
    AiCostReport,
    AiCostReportPeriod,
    BudgetPeriod,
    CostType,
    ModelCostRate,
    OptimizationStrategy,
    TokenCostBreakdown,
)
from eaip.ai_cost.service import AiCostService

__all__ = [
    "AiCostAlert",
    "AiCostAllocation",
    "AiCostAllocationError",
    "AiCostAllocationUpdated",
    "AiCostAnomalyDetected",
    "AiCostAnomalyError",
    "AiCostBudget",
    "AiCostBudgetAlertTriggered",
    "AiCostBudgetCreated",
    "AiCostBudgetError",
    "AiCostBudgetExceeded",
    "AiCostBudgetUpdated",
    "AiCostConfig",
    "AiCostDashboard",
    "AiCostDashboardUpdated",
    "AiCostError",
    "AiCostHealthCheck",
    "AiCostOptimizationApplied",
    "AiCostOptimizationError",
    "AiCostOptimizationRule",
    "AiCostOptimizationRuleCreated",
    "AiCostProjection",
    "AiCostProjectionComputed",
    "AiCostRecord",
    "AiCostRecordError",
    "AiCostRecorded",
    "AiCostReport",
    "AiCostReportError",
    "AiCostReportGenerated",
    "AiCostReportPeriod",
    "AiCostRuntimeModule",
    "AiCostService",
    "BudgetPeriod",
    "CostType",
    "ModelCostRate",
    "ModelCostRateUpdated",
    "OptimizationStrategy",
    "TokenCostBreakdown",
]
