"""AI Analytics & Insights — AI-specific metrics, usage, cost, latency, and anomaly detection."""

from eaip.ai_analytics.events import (
    AiAnalyticsConfigUpdated,
    AiAnalyticsDashboardCreated,
    AiAnalyticsDashboardUpdated,
    AiAnalyticsExportCompleted,
    AiAnalyticsForecastGenerated,
    AiAnalyticsInsightGenerated,
    AiAnalyticsMetricRecorded,
    AiAnalyticsReportGenerated,
    AiAnalyticsTrendComputed,
    AiAnomalyDetected,
    AiCostReported,
    AiErrorRateReported,
    AiLatencyReported,
    AiModelUsageReported,
    AiTokenUsageReported,
)
from eaip.ai_analytics.exceptions import (
    AiAnalyticsConfigError,
    AiAnalyticsDashboardError,
    AiAnalyticsError,
    AiAnalyticsExportError,
    AiAnalyticsMetricError,
    AiAnalyticsQueryError,
    AiAnalyticsReportError,
    AiAnomalyDetectionError,
)
from eaip.ai_analytics.health import AiAnalyticsHealthCheck
from eaip.ai_analytics.integration import AiAnalyticsRuntimeModule
from eaip.ai_analytics.models import (
    AiAnalyticsConfig,
    AiAnalyticsDashboard,
    AiAnalyticsDashboardWidget,
    AiAnalyticsExport,
    AiAnalyticsForecast,
    AiAnalyticsInsight,
    AiAnalyticsInsightSeverity,
    AiAnalyticsMetric,
    AiAnalyticsMetricType,
    AiAnalyticsReport,
    AiAnalyticsReportPeriod,
    AiAnalyticsTrend,
    AiAnomalyDetectionResult,
    AiCostMetrics,
    AiErrorMetrics,
    AiLatencyMetrics,
    AiModelUsageMetrics,
    AiTokenUsageMetrics,
)
from eaip.ai_analytics.service import AiAnalyticsService

__all__ = [
    "AiAnalyticsConfig",
    "AiAnalyticsConfigError",
    "AiAnalyticsConfigUpdated",
    "AiAnalyticsDashboard",
    "AiAnalyticsDashboardCreated",
    "AiAnalyticsDashboardError",
    "AiAnalyticsDashboardUpdated",
    "AiAnalyticsDashboardWidget",
    "AiAnalyticsError",
    "AiAnalyticsExport",
    "AiAnalyticsExportCompleted",
    "AiAnalyticsExportError",
    "AiAnalyticsForecast",
    "AiAnalyticsForecastGenerated",
    "AiAnalyticsHealthCheck",
    "AiAnalyticsInsight",
    "AiAnalyticsInsightGenerated",
    "AiAnalyticsInsightSeverity",
    "AiAnalyticsMetric",
    "AiAnalyticsMetricError",
    "AiAnalyticsMetricRecorded",
    "AiAnalyticsMetricType",
    "AiAnalyticsQueryError",
    "AiAnalyticsReport",
    "AiAnalyticsReportError",
    "AiAnalyticsReportGenerated",
    "AiAnalyticsReportPeriod",
    "AiAnalyticsRuntimeModule",
    "AiAnalyticsService",
    "AiAnalyticsTrend",
    "AiAnalyticsTrendComputed",
    "AiAnomalyDetected",
    "AiAnomalyDetectionError",
    "AiAnomalyDetectionResult",
    "AiCostMetrics",
    "AiCostReported",
    "AiErrorMetrics",
    "AiErrorRateReported",
    "AiLatencyMetrics",
    "AiLatencyReported",
    "AiModelUsageMetrics",
    "AiModelUsageReported",
    "AiTokenUsageMetrics",
    "AiTokenUsageReported",
]
